### PR TITLE
Fix: Better selection of live playhead tick interval time

### LINKED ISSUE #149: Bug: Instances De-sync at Switch to Live when Follower gets Bad Live Source Fetch
An issue arises when nodes switch to live and a Follower node, gets stuck in the
`"ALERT! Live Source Data NOT in sync! Will try again after X ms"` loop for a while. 

Now, what should happen is that the Follower would have received a Live manifest that is ahead of what the Leader got when it first requested for a live manifest. 
When this happens the engine will have the Follower 'drop' its manifest and use the live segments that the Leader stored in Redis instead.

This will ensure that, even though the Follower was slower in getting the correct segments, both nodes are in sync and will create the same manifests.

The Issue comes when the follower node's playhead tick interval is too long after this, relative to the live source tick interval. 
By default, the tick interval is 6 seconds on the first round. Furthermore, if there was a live source fetch desync, then the tick interval would be the full 6 seconds. Normally, the tick interval time would subtract the time it took to fetch the live manifest. 

During this long tick time, the leader could have already gone for another round of live segments before the follower could even read from the store.  This results in the Follower missing a vital round of stored live segments, and becoming desynced with the Leader.

### PR DESCRIPTION
**Pull request by Nfrederiksen**
PR should help fix #149 

I moved live segment duration calculation to after `_loadAllMediaManifest(.)`,
and also do not skip time compensation when fetch at live source is
not synced. I also removed old code for targetNumSeg

### CODE REVIEW

File: engine/session_live.js [hunk 1]
```diff
@@ -652,7 +644,6 @@ class SessionLive {
         // Wait a little before trying again
         debug(`[${this.sessionId}]: ALERT! Live Source Data NOT in sync! Will try again after ${retryDelayMs}ms`);
         await timer(retryDelayMs);
-        this.timerCompensation = false;
```
Comment (Nfrederiksen) [inline engine/session_live.js:655]: This was originally introduced as an attempt to lower the chances of trying to fetch when the live source is "out-of-sync" with its media manifests. But a live source can still be unpredictable, so might not need it.  Removing it shouldn't be a problem.

**Review by birme — APPROVED** [review]
Looks good!
