### PR TITLE
Fix: SessionLive - release segments based on duration not size, and more fixes

### LINKED ISSUE #145: SessionLive: Media Playlist - Slide Window Based On Total Duration Rather Than Number of Items
Currently, the manifests returned from sessionLive.js, slide the window of playlist segments based on item count.
eg.  if target_count is 10 and 2 new segments are added, then sessionLive will release the 2 top-most segments. 
Media-Sequence increments by 2.

This is different from how session.js (hls-vodtolive) does it, where it releases segments based on the total segment duration of all segments in the playlist.
eg. if target_duration is 60s. Current playlist contains 10 segments each 6s long, and 2 new segments (3s duration each) are added to the playlist, then only 1 top-most segment would be released since: 60 + 3 + 3 - 6 = target_duration 
Media-Sequence increments by 1.

Having different rules in session and sessionLive poses some issues when mix-switching back, if the durations of the segments in _v2l_ are much shorter than _live_

Suggest implementing the same rules in sessionLive as in session!

### PR DESCRIPTION
**Pull request by Nfrederiksen**
PR fixes #145 

But also some smaller bugs/issues related to the change

Other fixes made:
- Prevent Leader-node from replacing prev live-segments with empty list if Leader happens to receive the same mseq m3u8 from live source, causing de-synk with follower-node (line: 796 - sessionLive.js).
- More chances for a follower-node to clear vod cache. (line: 410 - session.js)
- When fetching and selecting `vodMediaSeqVideo` from currentVod to give to client, make sure that the `vodMediaSeqVideo` value is up-to-date and is correct for the currentVod in use. (line: 406 - session.js)
A timing specific issue would occur if the client requested for a manifest during the small window where the Leader-node had swapped out the stored currentVod but yet to update playheadState.vodMediaSeqVideo. This would Result in `getCurrentMediaManifestAsync(.)` getting the wrong mseq in the right currentVod

### CODE REVIEW

File: engine/session.js [hunk 1]
```diff
@@ -726,10 +739,11 @@ class Session {
         length = currentVod.getLiveMediaSequencesCount();
         lastDiscontinuity = currentVod.getLastDiscontinuity();
       }
+      await this._sessionState.set("state", SessionState.VOD_NEXT_INITIATING);
+      await this._sessionState.setCurrentVod(slateVod); 
+
```
Comment (Nfrederiksen) [inline engine/session.js:744]: Better to make sure that setting new current vod is done before setting new mseq values, everywhere

**Review by birme — APPROVED** [review]
Looks good!
