### PR TITLE
Fix: use dynamic delay time on media manifest load fail

### LINKED ISSUE #139: Time between Media Playlist loading tries are too long when live-source has short segment durations
Currently, when SessionLive is fetching/loading media playlists from the live-source, and they do not all comeback with the same 
`#EXT-X-MEDIA-SEQUENCE` value, then they are to retry the manifest loading operation after waiting 1500ms. 

However, for a source live stream with segment durations <4s, 1500ms might be too long, causing us to miss the window where the media playlists were all synced up. 
eg. 
... SessionLive fetches media playlist for all variants. Gets variant_1 w/ mseq:11, and variant_2 w/ mseq:12 
... Not in sync! Try again after 1500ms 
... SessionLive fetches media playlist for all variants. Gets variant_1 w/ mseq:12, and variant_2 w/ mseq:13 

We missed the window when both were w/ mseq:12 

I suggest that we have the time to wait depending on the duration of the newest Live source segment.

### PR DESCRIPTION
**Pull request by Nfrederiksen**
PR fixes #139 

The default sleep/delay time is set to 1500ms. Once some live segments are stored in SessionLive then the sleep time will be set according to the duration of the final segment * 0.25, a roughly fast enough time to better catch the sync window, and slow enough not to retry far too often.

### CODE REVIEW

File: engine/session_live.js [hunk 1]
```diff
@@ -663,16 +671,21 @@ class SessionLive {
...
       });
 
-
       // Handle if mediaSeqCounts are NOT synced up!
       if (!allMediaSeqCounts.every((val, i, arr) => val === arr[0])) {
-
         debug(`[${this.sessionId}]: Live Mseq counts=[${allMediaSeqCounts}]`);
         // Decrement fetch counter
         FETCH_ATTEMPTS--;
+        // Calculate retry delay time. Default=1500
```
Comment (Nfrederiksen) [inline engine/session_live.js:679]: Core fix is here
